WorkOrders.Website/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WorkOrders.Website.Models
{
    public class Customer
    {
        [Key]
        [Display(Name = "Customer #")]
        public Guid CustomerId { get; set; }

        [Display(Name = "Customer Name")]
        [Required(ErrorMessage = "Customer must have a name")]
        [StringLength(50, ErrorMessage = "The name you have is longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "Your name must be at least 3 characters long.")]
        public string CustomerName { get; set; }

        [Display(Name = "Phone Number (w/ Area Code)")]
        [Required(ErrorMessage = "You must enter a phone number!!!")]
        [StringLength(14, ErrorMessage = "Phone number cannot be longer than 14 characters")]
        [MinLength(10, ErrorMessage = "Phone number must be at least 10 digits")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(1-)?(\d{3}|\(\d{3}\) )-?\d{3}-?\d{4}$", 
            ErrorMessage = "Invalid phone number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Email Address")]
        [StringLength(200, ErrorMessage = "Email address cannot be longer than 200 characters")]
        [MinLength(6, ErrorMessage = "Email address must be at least 6 characters")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        [Display(Name = "Street Address")]
        [StringLength(100)]
        [MinLength(3)]
        public string StreetAddress1 { get; set; }
        [Display(Name = "Apt/Suite")]
        [StringLength(10)]
        [MinLength(1)]
        public string StreetAddress2 { get; set; }
        [StringLength(30)]
        public string City { get; set; }
        [StringLength(2)]
        [MinLength(2)]
        public string State { get; set; }
        [Display(Name = "Zip Code")]
        [RegularExpression(@"^(\d{4}-)?\d{5}$", ErrorMessage = "Invalid zip code")]
        [StringLength(10)]
        [MinLength(5)]
        [DataType(DataType.PostalCode)]
        public string ZipCode { get; set; }

        [Display(Name = "Image")]
        [StringLength(50, ErrorMessage = "Image name has to be shorter than 50 characters.")]
        [DataType(DataType.ImageUrl)]
        public string ImageName { get; set; }

        // Navigation

        [ForeignKey("CustomerId")]
        public virtual ICollection<Order> Orders { get; set; } 
    }
}

WorkOrders.Website/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WorkOrders.Website.Models;

namespace WorkOrders.Website.Controllers
{
    public class CustomerController : Controller
    {
        private WorkOrdersDatabase db = new WorkOrdersDatabase();

        // GET: Customer
        public ActionResult Index()
        {
            return View(
                db.Customers.OrderBy(x => x.CustomerName).ToList());
        }

        // GET: Customer/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        private void PopulateDropDowns()
        {
            string folderPath = Server.MapPath(Constants.CUSTOMER_FOLDER_PATH);
            ViewBag.Images = 
                Directory.EnumerateFiles(folderPath)
                         .Select(x => Path.GetFileName(x));
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            PopulateDropDowns();
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "CustomerId,ImageName,CustomerName,PhoneNumber,EmailAddress,StreetAddress1,StreetAddress2,City,State,ZipCode")]
            Customer customer,
            HttpPostedFileBase imageUpload)
        {
            customer.CustomerId = Guid.NewGuid();

            try
            {
                if (imageUpload != null &&
                    ValidateImage("ImageName", imageUpload))
                {
                    UploadCustomerImage(customer, imageUpload);
                }

                if (ModelState.IsValid)
                {
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(
                    "ImageName",
                    "Failed to save customer!"
                );
            }

            PopulateDropDowns();
            return View(customer);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            PopulateDropDowns();
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "CustomerId,ImageName,CustomerName,PhoneNumber,EmailAddress,StreetAddress1,StreetAddress2,City,State,ZipCode")]
            Customer customer,
            HttpPostedFileBase imageUpload)
        {
            try
            {
                if (imageUpload != null &&
                    ValidateImage("ImageName", imageUpload))
                {
                    UploadCustomerImage(customer, imageUpload);
                }

                if (ModelState.IsValid)
                {
                    db.Entry(customer).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(
                    "ImageName",
                    "Failed to save customer!"
                );
            }

            PopulateDropDowns();
            return View(customer);
        }

        private bool ValidateImage(string name, HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError(name, "Please select a file.");
                return false;
            }
            if (file.ContentLength <= 0)
            {
                ModelState.AddModelError(name, "File size was zero.");
                return false;
            }
            if (file.ContentLength >= Constants.MAX_UPLOAD_FILE_SIZE)
            {
                ModelState.AddModelError(name, "File size was to big.");
                return false;
            }

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            if (!Constants.ALLOWED_IMAGE_EXTENSIONS.Contains(fileExtension))
            {
                ModelState.AddModelError(name, $"File extension {fileExtension} not allowed.");
                return false;
            }

            return true;
        }

        private void UploadCustomerImage(Customer customer, HttpPostedFileBase file)
        {
            // Resize the image
            WebImage img = new WebImage(file.InputStream);
            if (img.Width > Constants.CUSTOMER_IMG_MAX_WIDTH || img.Height > 600)
            {
                img.Resize(350, 600);
            }

            // Save the image
            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            string fileName = $"CUSTOMER_{customer.CustomerId}{fileExtension}";
            img.Save(Constants.CUSTOMER_FOLDER_PATH + fileName);

            // Save the thumbnails
            img.Resize(100, 100);
            img.Save(Constants.CUSTOMER_FOLDER_PATH + Constants.THUMBNAILS_FOLDER + fileName);

            // Save the name of the image to the database
            customer.ImageName = fileName;
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkOrders.Website/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkOrders.Website.Models;

namespace WorkOrders.Website.Controllers
{
    public class OrderController : Controller
    {
        private WorkOrdersDatabase db = new WorkOrdersDatabase();

        // GET: Order
        public ActionResult Index()
        {
            return View(
                db.Orders.Include("Customer").ToList()
            );
        }

        // GET: Order/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        private void PopulateDropDowns()
        {
            ViewBag.Customers = new SelectList(
                db.Customers.OrderBy(x => x.CustomerName),
                "CustomerId",
                "CustomerName"
            );
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            PopulateDropDowns();
            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,CustomerId,DateOfRepair,WrittenBy,Year,Make,Model,LicensePlate,Mileage,EstimateAmount,TotalLaborCost,TotalPartCost,TaxAmount,LUBE,OIL_CHANGE,FLUSH_TRANSMISSION,FLUSH_DIFFERENTIAL,WASH,POLISH")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.OrderId = Guid.NewGuid();
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateDropDowns();
            return View(order);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            PopulateDropDowns();
            return View(order);
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "OrderId,CustomerId,DateOfRepair,WrittenBy,Year,Make,Model,LicensePlate,Mileage,EstimateAmount,TotalLaborCost,TotalPartCost,TaxAmount,LUBE,OIL_CHANGE,FLUSH_TRANSMISSION,FLUSH_DIFFERENTIAL,WASH,POLISH,FormFileName")]
            Order order,
            HttpPostedFileBase formUpload)
        {
            try
            {
                if (formUpload != null &&
                    ValidateFile("FormFileName", formUpload))
                {
                    UploadFile(order, formUpload);
                }

                if (ModelState.IsValid)
                {
                    db.Entry(order).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(
                    "FormFileName",
                    "Failed to save order!"
                );
            }

            PopulateDropDowns();
            return View(order);
        }

        private bool ValidateFile(string name, HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError(name, "Please select a file.");
                return false;
            }
            if (file.ContentLength <= 0)
            {
                ModelState.AddModelError(name, "File size was zero.");
                return false;
            }
            if (file.ContentLength >= Constants.MAX_UPLOAD_FILE_SIZE)
            {
                ModelState.AddModelError(name, "File size was to big.");
                return false;
            }

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            if (!Constants.ALLOWED_FORM_EXTENSIONS.Contains(fileExtension))
            {
                ModelState.AddModelError(name, $"File extension {fileExtension} not allowed.");
                return false;
            }

            return true;
        }

        private void UploadFile(Order order, HttpPostedFileBase file)
        {
            string folderPath = Server.MapPath(Constants.ORDER_FOLDER_PATH);

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            string fileName = $"FORM_{order.OrderId}{fileExtension}";
            string filePath = Path.Combine(folderPath, fileName);
            file.SaveAs(filePath);
            order.FormFileName = fileName;
        }

        // GET: Order/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkOrders.Website/Views/Customer/Create.cshtml
@model WorkOrders.Website.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Customer", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control", list = "images" } })
                <input type="file" name="imageUpload" class="form-control-file" />
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<datalist id="images">
    @foreach (string image in ViewBag.Images)
    {
        <option value="@image">@image</option>
    }
</datalist>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkOrders.Website/Views/Customer/Delete.cshtml
@model WorkOrders.Website.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WorkOrders.Website/Views/Customer/Details.cshtml
@model WorkOrders.Website.Models.Customer
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @if (!string.IsNullOrWhiteSpace(Model.ImageName))
            {
                string url = Url.Content(
                    Constants.CUSTOMER_FOLDER_PATH +
                    Model.ImageName);
                <img src="@url" />
            }
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

    </dl>
</div>

<!-- Orders -->
<table class="table">
    <tr>
        <th>
            Date of Repair
        </th>
        <th>
            Written By
        </th>
        <th>
            Year
        </th>
        <th>
            Make
        </th>
        <th>
            Model
        </th>
        <th>
            Mileage
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Orders)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfRepair)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WrittenBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mileage)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Order", new { id = item.OrderId }, null) |
                @Html.ActionLink("Details", "Details", "Order", new { id = item.OrderId }, null) |
                @Html.ActionLink("Delete", "Delete", "Order", new { id = item.OrderId }, null)
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorkOrders.Website/Views/Customer/Edit.cshtml
@model WorkOrders.Website.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Customer", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerId)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control", list = "images" } })
                <input type="file" name="imageUpload" class="form-control-file" />
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<datalist id="images">
    @foreach (string image in ViewBag.Images)
    {
        <option value="@image">@image</option>
    }
</datalist>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}